---

- name: baseline configuration
  hosts: "{{ nodes }}"

  pre_tasks:

    - name: source pre-playbook tasks
      ansible.builtin.include_tasks:
        file: task__pre.yml

    - name: source bazzite fixes
      ansible.builtin.include_tasks:
        file: task__pre_bazzite_fix.yml

    - name: source steamos tasks
      ansible.builtin.include_tasks:
        file: task__pre_steamos.yml

  tasks:

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

  post_tasks:

    - name: source post-playbook tasks
      ansible.builtin.include_tasks:
        file: task__post.yml

...
