---

- name: deploy baseline configuration
  ansible.builtin.import_playbook: node__baseline.yml

- name: desktop configuration
  hosts: "{{ nodes }}"

  tasks:

    - name: deploy desktop environment
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: desktop.yml

...
