---

- name: deploy custom configuration
  hosts: "{{ nodes }}"

  pre_tasks:

    - name: source pre-playbook tasks
      ansible.builtin.include_tasks:
        file: task__pre.yml

    - name: remove rescue kernel(s)
      ansible.builtin.include_role:
        name: boot_loader
        tasks_from: remove_rescue_kernels.yml

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

    - name: deploy desktop environment
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: desktop.yml

  tasks:

    - name: ensure tasks run only on selected os releases
      block:

        - name: deploy wireguard
          ansible.builtin.include_role:
            name: vpn_tunnel
            tasks_from: wireguard_deploy.yml
          vars:
            hide_secrets: false

        - name: install nerdfonts
          ansible.builtin.include_role:
            name: cli_customization
            tasks_from: nerdfont_install.yml
          vars:
            font_name: sauce_code_pro
            font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/SourceCodePro.zip"

        - name: deploy preferred text editor
          ansible.builtin.include_tasks:
            file: task__editor.yml

        - name: deploy preferred terminal multiplexer
          ansible.builtin.include_tasks:
            file: task__multiplexer.yml

        - name: deploy preferred shell
          ansible.builtin.include_tasks:
            file: task__shell.yml

        - name: deploy system-wide known hosts keys
          ansible.builtin.include_tasks:
            file: task__ssh_keyscan.yml

        - name: define additional packages
          ansible.builtin.set_fact:
            common_packages:
              - unrar
              - unzip

        - name: define additional fedora packages
          ansible.builtin.set_fact:
            fedora_packages:
              - p7zip
          when: ansible_distribution == "Fedora"

        - name: define additional steamos packages
          ansible.builtin.set_fact:
            steamos_packages:
              - 7zip
          when:
            - ansible_distribution == "Archlinux"
            - ansible_distribution_release == "holo"

        - name: install additional fedora packages
          ansible.builtin.package:
            name: "{{ common_packages | community.general.lists_union(fedora_packages) }}"
            state: present
          when: ansible_distribution == "Fedora"

        - name: install additional steamos packages
          ansible.builtin.package:
            name: "{{ common_packages | community.general.lists_union(steamos_packages) }}"
            state: present
          when:
            - ansible_distribution == "Archlinux"
            - ansible_distribution_release == "holo"

        - name: ensure tasks run only on selected os releases
          block:

            - name: disable zram
              ansible.builtin.file:
                path: /etc/systemd/zram-generator.conf
                state: touch

            - name: configure anydesk repository
              ansible.builtin.yum_repository:
                name: anydesk
                description: AnyDesk Fedora - stable
                file: fedora-anydesk
                baseurl: http://rpm.anydesk.com/rhel/8/$basearch/
                gpgkey: https://keys.anydesk.com/repos/RPM-GPG-KEY
                gpgcheck: true
                repo_gpgcheck: true
                metadata_expire: 21600

            - name: install anydesk
              ansible.builtin.package:
                name: anydesk
                state: present

            - name: enable spotify repository
              ansible.builtin.command:
                cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
              when:
              - ansible_distribution_major_version < "41"

            - name: enable spotify repository
              ansible.builtin.command:
                cmd: dnf config-manager addrepo --overwrite --from-repofile=https://negativo17.org/repos/fedora-spotify.repo
              when:
              - ansible_distribution_major_version >= "41"

            - name: install spotify
              ansible.builtin.package:
                name: spotify-client
                state: present

            - name: enable teams for linux repository
              ansible.builtin.command:
                cmd: dnf config-manager --add-repo=https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
              when:
              - ansible_distribution_major_version < "41"

            - name: enable teams for linux repository
              ansible.builtin.command:
                cmd: dnf config-manager addrepo --overwrite --from-repofile=https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
              when:
              - ansible_distribution_major_version >= "41"

            - name: add gpg keys for the teams for linux repository
              ansible.builtin.lineinfile:
                path: /etc/yum.repos.d/teams-for-linux.repo
                state: present
                regexp: "^gpgkey="
                insertafter: "^gpgcheck="
                line: "gpgkey=https://repo.teamsforlinux.de/teams-for-linux.asc"

            - name: install teams for linux
              ansible.builtin.package:
                name: teams-for-linux
                state: present

            - name: fix for libdnf issues when installing via urls
              block:

                - name: install viber
                  ansible.builtin.package:
                    name: https://download.cdn.viber.com/desktop/Linux/viber.rpm
                    state: present
                    disable_gpg_check: true

              rescue:

                - name: install viber via dnf
                  ansible.builtin.command:
                    cmd: "dnf install -y https://download.cdn.viber.com/desktop/Linux/viber.rpm"

            - name: install desktop application(s)
              ansible.builtin.package:
                name:
                  - electrum
                  - firefox
                  - gimp
                  - inkscape
                  - "@LibreOffice"
                state: present

            - name: install steam
              ansible.builtin.include_role:
                name: linux_gaming
                tasks_from: steam_install.yml

            - name: allow running steam via sudo
              ansible.builtin.include_role:
                name: linux_gaming
                tasks_from: steam_sudo.yml

            - name: install xone dongle/gamepad driver
              ansible.builtin.include_role:
                name: linux_gaming
                tasks_from: xone_driver.yml

            - name: install qemu-kvm
              ansible.builtin.include_role:
                name: linux_virtualization
                tasks_from: kvm.yml

            - name: configure kvm bridge on default network interface
              ansible.builtin.include_role:
                name: linux_virtualization
                tasks_from: default_bridge.yml
              vars:
                enable_network_bridge: true

          when: ansible_distribution == "Fedora"

      when: >
        (ansible_distribution == "Archlinux" and ansible_distribution_release == "holo") or
        ansible_distribution == "Fedora"

  post_tasks:

    - name: source post-playbook tasks
      ansible.builtin.include_tasks:
        file: task__post.yml

...
