---

- name: deploy base desktop configuration
  ansible.builtin.import_playbook: node__desktop.yml

- name: deploy custom desktop configuration
  hosts: "{{ nodes }}"

  tasks:

    - name: install steam
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: steam_install.yml

    - name: allow running steam via sudo
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: steam_sudo.yml

    - name: install xone dongle/gamepad driver
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: xone_driver.yml

    - name: install powerline
      ansible.builtin.include_role:
        name: cli_customization
        tasks_from: powerline_install.yml

...
