---

- name: baseline configuration
  hosts: "{{ nodes }}"

  pre_tasks:

    - name: source pre-playbook tasks
      ansible.builtin.include_tasks:
        file: task__pre.yml

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

  tasks:

    - name: install qemu-kvm
      ansible.builtin.include_role:
        name: linux_virtualization
        tasks_from: kvm.yml

    - name: configure kvm bridge on default network interface
      ansible.builtin.include_role:
        name: linux_virtualization
        tasks_from: default_bridge.yml
      vars:
        enable_network_bridge: true

  post_tasks:

    - name: source post-playbook tasks
      ansible.builtin.include_tasks:
        file: task__post.yml

...
