---

- name: deploy custom configuration
  hosts: "{{ nodes }}"

  pre_tasks:

    - name: source pre-playbook tasks
      ansible.builtin.include_tasks:
        file: task__pre.yml

    - name: source bazzite fixes
      ansible.builtin.include_tasks:
        file: task__pre_bazzite_fix.yml

    - name: source steamos tasks
      ansible.builtin.include_tasks:
        file: task__pre_steamos.yml

    - name: remove rescue kernel(s)
      ansible.builtin.include_role:
        name: boot_loader
        tasks_from: remove_rescue_kernels.yml

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

    - name: deploy desktop environment
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: desktop.yml

  tasks:

    - name: ensure tasks run only on selected os releases
      block:

        - name: install nerdfonts
          ansible.builtin.include_role:
            name: cli_customization
            tasks_from: nerdfont_install.yml
          vars:
            font_name: sauce_code_pro
            font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/SourceCodePro.zip"

        - name: deploy preferred text editor
          ansible.builtin.include_tasks:
            file: task__editor.yml

        - name: deploy preferred terminal multiplexer
          ansible.builtin.include_tasks:
            file: task__multiplexer.yml

        - name: deploy preferred shell
          ansible.builtin.include_tasks:
            file: task__shell.yml

        - name: deploy system-wide known hosts keys
          ansible.builtin.include_tasks:
            file: task__ssh_keyscan.yml

        - name: define additional packages
          ansible.builtin.set_fact:
            common_packages:
              - unrar
              - unzip
          when: ansible_distribution != "Bazzite"

        - name: define additional fedora packages
          ansible.builtin.set_fact:
            fedora_packages:
              - p7zip
          when: ansible_distribution == "Fedora"

        - name: define additional steamos packages
          ansible.builtin.set_fact:
            steamos_packages:
              - 7zip
          when:
            - ansible_distribution == "Archlinux"
            - ansible_distribution_release == "holo"

        - name: install additional fedora packages
          ansible.builtin.package:
            name: "{{ common_packages | community.general.lists_union(fedora_packages) }}"
            state: present
          when: ansible_distribution == "Fedora"

        - name: install additional steamos packages
          ansible.builtin.package:
            name: "{{ common_packages | community.general.lists_union(steamos_packages) }}"
            state: present
          when:
            - ansible_distribution == "Archlinux"
            - ansible_distribution_release == "holo"

        - name: ensure tasks run only on selected os releases
          block:

            - name: disable zram
              ansible.builtin.file:
                path: /etc/systemd/zram-generator.conf
                state: touch

            #- name: enable teams for linux repository
            #  ansible.builtin.command:
            #    cmd: dnf config-manager --add-repo=https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
            #  when:
            #  - ansible_distribution_major_version < "41"

            #- name: enable teams for linux repository
            #  ansible.builtin.command:
            #    cmd: dnf config-manager addrepo --overwrite --from-repofile=https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
            #  when:
            #  - ansible_distribution_major_version >= "41"

            #- name: add gpg keys for the teams for linux repository
            #  ansible.builtin.lineinfile:
            #    path: /etc/yum.repos.d/teams-for-linux.repo
            #    state: present
            #    regexp: "^gpgkey="
            #    insertafter: "^gpgcheck="
            #    line: "gpgkey=https://repo.teamsforlinux.de/teams-for-linux.asc"

            #- name: install teams for linux
            #  ansible.builtin.package:
            #    name: teams-for-linux
            #    state: present

          when: ansible_distribution == "Fedora"

        - name: deploy personal customizations
          ansible.builtin.include_tasks:
            file: task__personal_customization.yml

      when: >
        (ansible_distribution == "Archlinux" and ansible_distribution_release == "holo") or
        ansible_distribution == "Bazzite" or
        ansible_distribution == "Fedora"

  post_tasks:

    - name: source post-playbook tasks
      ansible.builtin.include_tasks:
        file: task__post.yml

...
