---

- name: baseline configuration
  hosts: "{{ nodes }}"

  tasks:

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

    - name: deploy desktop environment
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: desktop.yml

...
