---

- name: baseline configuration
  hosts: "{{ nodes }}"

  tasks:

    - name: disable steam deck readonly protection
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: steam_deck_readonly_toggle.yml

    - name: initialize steam deck repositories
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: steam_deck_repository.yml

    - name: deploy baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

    - name: install qemu-kvm
      ansible.builtin.include_role:
        name: linux_virtualization
        tasks_from: kvm.yml

    - name: configure kvm bridge on default network interface
      ansible.builtin.include_role:
        name: linux_virtualization
        tasks_from: default_bridge.yml
      vars:
        enable_network_bridge: true

...
