---

- name: baseline configuration
  hosts: "{{ nodes }}"

  tasks:

    - name: configure baseline configuration
      ansible.builtin.include_role:
        name: number_cruncher
        tasks_from: baseline.yml
      vars:
        fqdn_hostname: false

...
