---

- name: identify os id
  ansible.builtin.shell:
    cmd: "grep ^ID= /etc/os-release | sed -e 's/ID=//' -e 's/\"//g' -e \"s/'//g\""
  register: os_id
  changed_when: false

- name: display os id
  ansible.builtin.debug:
    var: os_id.stdout
    verbosity: 1

- name: ensure tasks run only on selected os releases
  block:

    - name: disable steam deck readonly protection
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: steam_deck_readonly_disable.yml

    - name: initialize steam deck repositories
      ansible.builtin.include_role:
        name: linux_gaming
        tasks_from: steam_deck_repository.yml

  when: os_id.stdout == "steamos"

- name: create temporary work directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible_
    suffix: _deleteme
  register: ansible_work_dir
  vars:
    ansible_become: false

...
