---

# dummy task to check if this is a bazzite system
# "check_mode:" true ensures that /etc/os-release is never modified
- name: check if this is a bazzite system
  ansible.builtin.lineinfile:
    path: /etc/os-release
    regexp: '^(.*)Bazzite(.*)'
    state: absent
  check_mode: true
  register: bazzite_check

- name: display bazzite_check result
  ansible.builtin.debug:
    var: bazzite_check
    verbosity: 1

# on bazzite systems ansible_distribution gets confused with
# the fedora entry in /etc/redhat-release -  so delete it
- name: remove release aliases
  ansible.builtin.file:
    path: "/etc/{{ item }}-release"
    state: absent
  loop:
    - fedora
    - redhat
    - system
  when: bazzite_check.changed

- name: bazzite fixes and work arounds
  block:

    # topgrade requires password input for privilege escalation
    # ensure that the ansible user requires no password under sudo
    - name: "ensure sudo via {{ ansible_user }} requires no password"
      ansible.builtin.copy:
        content: "{{ ansible_user }}	ALL=(ALL)	NOPASSWD: ALL"
        dest: "/etc/sudoers.d/{{ ansible_user }}"

    - name: deploy homebrew ownership fix
      block:

        - name: "ensure /home/linuxbrew is owned by {{ ansible_user }}"
          ansible.builtin.file:
            path: /home/linuxbrew
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            recurse: true

      rescue:

        - name: "ensure /home/linuxbrew is owned by {{ ansible_user }}"
          ansible.builtin.command:
            cmd: "chown -R {{ ansible_user }}:{{ ansible_user }} /home/linuxbrew"

    # running topgrade as root will cause flatpak updates to fail
    # for now system and firmware updates are done as root while
    # flatpak, homebrew, and custom commands are done with user privs
    - name: deploy topgrade customization
      block:

        - name: get default topgrade configuration
          ansible.builtin.shell:
            cmd: "ujust --show update | grep topgrade | xargs | cut -d ' ' -f 3"
          register: topgrade_config
          changed_when: false

        - name: create topgrade root configuration
          ansible.builtin.shell:
            cmd: >
              sed
              -e 's/"flatpak", //'
              -e 's/, "flatpak"//'
              -e 's/"brew_cask", //'
              -e 's/, "brew_cask"//'
              -e 's/"brew_formula", //'
              -e 's/, "brew_formula"//'
              -e 's/"custom_commands", //'
              -e 's/, "custom_commands"//'
              {{ topgrade_config.stdout }} >
              {{ ansible_work_dir.path }}/topgrade_root.toml

        - name: create topgrade user configuration
          ansible.builtin.shell:
            cmd: >
              sed
              -e 's/"system", //'
              -e 's/, "system"//'
              -e 's/"firmware", //'
              -e 's/, "firmware"//'
              {{ topgrade_config.stdout }} >
              {{ ansible_work_dir.path }}/topgrade_user.toml

      vars:
        ansible_become: false

  when: ansible_distribution == "Bazzite"

...
