---

- name: remove temporary work directory
  ansible.builtin.file:
    path: "{{ ansible_work_dir.path }}"
    state: absent

- name: enable steam deck readonly protection
  ansible.builtin.include_role:
    name: linux_gaming
    tasks_from: steam_deck_readonly_enable.yml
  when:
    - ansible_distribution == "Archlinux"
    - ansible_distribution_release == "holo"

- name: display post run message(s)
  ansible.builtin.debug:
    var: post_run_message
  when:
    - post_run_message is defined
    - post_run_message != ""
  delegate_to: localhost
  run_once: true

...
