---

- name: ensure tasks run only on selected os releases
  block:

    - name: deploy neovim
      ansible.builtin.include_role:
        name: cli_customization
        tasks_from: neovim_deploy.yml
      vars:
        nvim_dir_home: "~/.config/nvim"
        nvim_dir_config: "configs"
        nvim_dir_plugin: "plugins"
        nvim_dir_ftype: "after/ftplugin"
        nvim_config_generator: "/etc/profile.d/neovim_config_generator.sh"
        nvim_config_location:
          - "{{ nvim_dir_home }}/{{ nvim_dir_ftype }}"
          - "{{ nvim_dir_home }}/lua/{{ nvim_dir_config }}"
          - "{{ nvim_dir_home }}/lua/{{ nvim_dir_plugin }}"
        nvim_config_file:
          - name: "{{ nvim_dir_home }}/init.lua"
            data: |
              -- load defaults
              require("{{ nvim_dir_config }}.default")

              -- load plugin manager
              require("{{ nvim_dir_config }}.lazy")

              -- load plugins
              require("{{ nvim_dir_config }}.bufferline")
              require("{{ nvim_dir_config }}.lualine")
          - name: "{{ nvim_dir_home }}/lua/{{ nvim_dir_config }}/default.lua"
            data: |
              -- background setting(s)
              vim.api.nvim_set_hl(0, "Normal", {bg = "none"})
              vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
              vim.api.nvim_set_hl(0, "StatusLine", { bg = "none" })
              vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "none" })
              vim.api.nvim_set_hl(0, "TabLineFill", { bg = "none" })

              -- indicator setting(s)
              vim.opt.guicursor = "n-v-c-i:block"
              vim.opt.cursorcolumn = true
              vim.opt.cursorline = true
              vim.opt.number = true
              vim.opt.list = true
              vim.opt.listchars = { tab = "| " }

              -- fold setting(s)
              vim.opt.foldmethod = "indent"
              vim.opt.foldlevelstart = 9999

              -- keymap setting(s)
              -- toggle visual aids
              vim.keymap.set("n", "<tab>", ":set number! <bar> :set list! <bar> :set cursorcolumn! <bar> :set cursorline! <CR>")
              -- toggle folds
              vim.keymap.set("n", "<space>", "za")
              -- move to prev buffer
              vim.keymap.set("n", "<c-right>", ":BufferLineCycleNext<CR>")
              -- move to next buffer
              vim.keymap.set("n", "<c-left>", ":BufferLineCyclePrev<CR>")
              -- split - move to left
              vim.keymap.set("n", "<c-s-left>", "<c-w>h")
              -- split - move to right
              vim.keymap.set("n", "<c-s-right>", "<c-w>l")
              -- split - move to top
              vim.keymap.set("n", "<c-s-up>", "<c-w>k")
              -- split - move to bottom
              vim.keymap.set("n", "<c-s-down>", "<c-w>j")

              -- mouse setting(s)
              vim.opt.mouse = ""

              -- split setting(s)
              vim.opt.splitbelow = true
              vim.opt.splitright = true

              -- tab setting(s)
              vim.opt.tabstop = 4
              vim.opt.softtabstop = 0
              vim.opt.shiftwidth = 4
              vim.opt.expandtab = false

              -- terminal setting(s)
              vim.opt.shell = "/bin/env bash -l"
          - name: "{{ nvim_dir_home }}/lua/{{ nvim_dir_config }}/lazy.lua"
            data: |
              -- Bootstrap lazy.nvim
              local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
              if not (vim.uv or vim.loop).fs_stat(lazypath) then
                  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
                  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
                  if vim.v.shell_error ~= 0 then
                      vim.api.nvim_echo({
                          { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
                          { out, "WarningMsg" },
                          { "\nPress any key to exit..." },
                      }, true, {})
                      vim.fn.getchar()
                      os.exit(1)
                  end
              end

              vim.opt.rtp:prepend(lazypath)

              -- Make sure to setup mapleader and maplocalleader before
              -- loading lazy.nvim so that mappings are correct.
              -- This is also a good place to setup other settings (vim.opt)
              vim.g.mapleader = " "
              vim.g.maplocalleader = "\\\"

              -- Setup lazy.nvim
              require("lazy").setup({
                  spec = {
                      -- import your plugins
                      { import = "plugins" },
                  },
                  -- Configure any other settings here. See the documentation for more details.
                  -- colorscheme that will be used when installing plugins.
                  install = { colorscheme = { "habamax" } },
                  -- automatically check for plugin updates
                  checker = { enabled = true },
              })
          - name: "{{ nvim_dir_home }}/lua/{{ nvim_dir_config }}/bufferline.lua"
            data: |
              vim.opt.termguicolors = true

              require("bufferline").setup{
                  options = {
                      mode = "buffers",
                      numbers = "buffer_id",
                      left_mouse_command = false,
                      right_mouse_command = false,
                      indicator = { style = "underline" },
                      show_buffer_icons = false,
                      show_buffer_close_icons = false
                  },
                  highlights = {
                      buffer_selected = {
                          fg = "#00afd7",
                          italic = false
                      },
                      numbers_selected = {
                          fg = "#00afd7",
                          italic = false
                      }
                  }
              }
          - name: "{{ nvim_dir_home }}/lua/{{ nvim_dir_config }}/lualine.lua"
            data: |
              local color = {
                  t33  = "#0087ff",
                  t37  = "#00afaf",
                  t38  = "#00afd7",
                  t73  = "#5fafaf",
                  t98  = "#875fd7",
                  t166 = "#d75f00",
                  t255 = "#eeeeee"
              }
              local basic = {
                  normal = {
                      a = { fg = color.t73 },
                      b = { fg = color.t38 },
                      c = { fg = color.t255 }
                  },
                  insert = { a = { fg = color.t37 } },
                  visual = { a = { fg = color.t98 } },
                  replace = { a = { fg = color.t166 } },
                  inactive = {
                      a = { fg = color.t255 },
                      b = { fg = color.t255 },
                      c = { fg = color.t255 }
                  }
              }
              require("lualine").setup {
                  options = {
                      icons_enabled = true,
                      theme = basic,
                      component_separators = { left = " ", right = " " },
                      section_separators = { left = " ", right = " " },
                      disabled_filetypes = {
                          statusline = {},
                          winbar = {},
                      },
                      ignore_focus = {},
                      always_divide_middle = true,
                      always_show_tabline = true,
                      globalstatus = false,
                      refresh = {
                          statusline = 100,
                          tabline = 100,
                          winbar = 100,
                      }
                  },
                  sections = {
                      lualine_a = {"mode"},
                      lualine_b = {"branch", "diff", "diagnostics"},
                      lualine_c = {"filename"},
                      lualine_x = {"encoding", "fileformat", "filetype"},
                      lualine_y = {"progress"},
                      lualine_z = {"location"}
                  },
                  inactive_sections = {
                      lualine_a = {},
                      lualine_b = {},
                      lualine_c = {"filename"},
                      lualine_x = {"location"},
                      lualine_y = {},
                      lualine_z = {}
                  },
                  tabline = {},
                  winbar = {},
                  inactive_winbar = {},
                  extensions = {}
              }
          - name: "{{ nvim_dir_home }}/lua/{{ nvim_dir_plugin }}/default.lua"
            data: |
              return {
                  -- bufferline
                  {"akinsho/bufferline.nvim", version = "*", dependencies = "nvim-tree/nvim-web-devicons"},
                  -- lualine
                  {"nvim-lualine/lualine.nvim", dependencies = "nvim-tree/nvim-web-devicons"},
                  -- vim-fugitive
                  { "tpope/vim-fugitive" }
              }
          - name: "{{ nvim_dir_home }}/{{ nvim_dir_ftype }}/bash.lua"
            data: |
              vim.opt_local.tabstop = 4
              vim.opt_local.softtabstop = 0
              vim.opt_local.shiftwidth = 4
              vim.opt_local.expandtab = false
          - name: "{{ nvim_dir_home }}/{{ nvim_dir_ftype }}/markdown.lua"
            data: |
              vim.opt_local.tabstop = 2
              vim.opt_local.softtabstop = 2
              vim.opt_local.shiftwidth = 2
              vim.opt_local.expandtab = true
          - name: "{{ nvim_dir_home }}/{{ nvim_dir_ftype }}/sh.lua"
            data: |
              vim.opt_local.tabstop = 4
              vim.opt_local.softtabstop = 0
              vim.opt_local.shiftwidth = 4
              vim.opt_local.expandtab = false
          - name: "{{ nvim_dir_home }}/{{ nvim_dir_ftype }}/yaml.lua"
            data: |
              vim.opt_local.tabstop = 2
              vim.opt_local.softtabstop = 2
              vim.opt_local.shiftwidth = 2
              vim.opt_local.expandtab = true

    - name: set post run message
      ansible.builtin.set_fact:
        post_run_message: |
          {{ post_run_message | default('') }}
          ---------- to configure neovim ----------
          | create the trigger file:
          touch "$HOME/.customize_text_editor"

  when: >
    (ansible_distribution == "Archlinux" and ansible_distribution_release == "holo") or
    ansible_distribution == "Bazzite" or
    ansible_distribution == "Fedora"

...
