---

- name: identify os id
  ansible.builtin.shell:
    cmd: "grep ^ID= /etc/os-release | sed -e 's/ID=//' -e 's/\"//g' -e \"s/'//g\""
  register: os_id
  changed_when: false

- name: display os id
  ansible.builtin.debug:
    var: os_id.stdout
    verbosity: 1

- name: create temporary work directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible_
    suffix: _deleteme
  register: ansible_work_dir
  vars:
    ansible_become: false

...
